<?php

namespace App\Services;

use App\Models\Account;
use App\Models\ExpenseCategory;
use App\Models\IncomeCategory;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class IncomeExpenseImportService
{
    public const HEADERS = [
        'date_ad',
        'category',
        'account',
        'amount',
        'reference',
        'note',
    ];

    public function __construct(
        private readonly FinancialDateService $dates,
        private readonly IncomeService $incomeService,
        private readonly ExpenseService $expenseService
    ) {
    }

    public function template(string $type): BinaryFileResponse
    {
        $label = $this->label($type);
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet()->setTitle($label);

        foreach (self::HEADERS as $index => $header) {
            $sheet->setCellValueExplicit([$index + 1, 1], $header, DataType::TYPE_STRING);
        }

        $sheet->getStyle('A1:F1')->getFont()->setBold(true);
        $sheet->freezePane('A2');
        $instructions = $spreadsheet->createSheet()->setTitle('Instructions');
        $instructions->fromArray([
            ["{$label} Import Instructions"],
            ["Use the {$label} sheet without changing or reordering headers."],
            ['date_ad, category code, account code, and amount are required.'],
            ['Maximum 500 rows and 5 MB. Amount must be a positive whole number.'],
            ['Date BS, Financial Year, transaction number, balances, and ledger entries are generated by the application.'],
        ]);
        $instructions->getColumnDimension('A')->setWidth(120);
        $instructions->getStyle('A1')->getFont()->setBold(true);

        $path = tempnam(sys_get_temp_dir(), strtolower($type).'-template-');
        (new Xlsx($spreadsheet))->save($path);
        $spreadsheet->disconnectWorksheets();

        return response()->download(
            $path,
            strtolower($type).'-import-template.xlsx'
        )->deleteFileAfterSend(true);
    }

    public function validateWorkbook(UploadedFile $file, string $type): array
    {
        try {
            $reader = IOFactory::createReaderForFile($file->getRealPath());
            if (! $reader instanceof \PhpOffice\PhpSpreadsheet\Reader\Xlsx) {
                throw new \RuntimeException('Unsupported workbook type.');
            }
            $reader->setReadDataOnly(true);
            $spreadsheet = $reader->load($file->getRealPath());
        } catch (\Throwable) {
            throw ValidationException::withMessages([
                'file' => 'The uploaded file is not a valid XLSX workbook.',
            ]);
        }

        $sheet = $spreadsheet->getSheetByName($this->label($type))
            ?? $spreadsheet->getActiveSheet();
        $highestColumn = $sheet->getHighestDataColumn();
        $headers = array_map(
            fn ($value) => trim((string) $value),
            $sheet->rangeToArray("A1:{$highestColumn}1", null, true, false)[0] ?? []
        );

        if ($headers !== self::HEADERS) {
            $spreadsheet->disconnectWorksheets();
            throw ValidationException::withMessages([
                'file' => "Workbook headers do not exactly match the {$this->label($type)} template.",
            ]);
        }

        $rawRows = [];
        for ($rowNumber = 2; $rowNumber <= $sheet->getHighestDataRow(); $rowNumber++) {
            $values = $sheet->rangeToArray("A{$rowNumber}:F{$rowNumber}", null, true, false)[0];
            if (collect($values)->every(fn ($value) => blank($value))) {
                continue;
            }
            $rawRows[$rowNumber] = array_combine(
                self::HEADERS,
                array_map(fn ($value) => is_string($value) ? trim($value) : $value, $values)
            );
        }
        $spreadsheet->disconnectWorksheets();

        if (count($rawRows) > 500) {
            throw ValidationException::withMessages([
                'file' => "The workbook exceeds the maximum of 500 {$type} rows.",
            ]);
        }

        $categoryModel = $type === 'income' ? IncomeCategory::class : ExpenseCategory::class;
        $categories = $categoryModel::query()
            ->where('is_active', true)
            ->get()
            ->keyBy('code');
        $accounts = Account::query()
            ->where('is_active', true)
            ->get()
            ->keyBy('code');
        $runningBalances = $accounts->mapWithKeys(
            fn (Account $account) => [$account->code => (int) $account->current_balance]
        )->all();
        $rows = [];
        $errors = [];
        $workbookRows = [];

        foreach ($rawRows as $rowNumber => $row) {
            $validator = Validator::make($row, [
                'date_ad' => ['required', 'date_format:Y-m-d'],
                'category' => ['required', 'string', 'max:50'],
                'account' => ['required', 'string', 'max:50'],
                'amount' => ['required', 'integer', 'min:1'],
                'reference' => ['nullable', 'string', 'max:100'],
                'note' => ['nullable', 'string', 'max:2000'],
            ]);

            foreach ($validator->errors()->all() as $message) {
                $errors[] = "Row {$rowNumber}: {$message}";
            }
            if ($validator->fails()) {
                continue;
            }

            $fingerprint = hash('sha256', json_encode(array_values($row)));
            if (isset($workbookRows[$fingerprint])) {
                $errors[] = "Row {$rowNumber}: Duplicate workbook row.";
            }
            $workbookRows[$fingerprint] = true;

            $category = $categories->get((string) $row['category']);
            $account = $accounts->get((string) $row['account']);

            if (! $category) {
                $errors[] = "Row {$rowNumber}: Active {$type} category code {$row['category']} was not found.";
            }
            if (! $account) {
                $errors[] = "Row {$rowNumber}: Active account code {$row['account']} was not found.";
            } elseif ($account->type === Account::TYPE_FIXED_DEPOSIT) {
                $errors[] = "Row {$rowNumber}: Fixed Deposit account cannot be used for {$type}.";
            }

            $date = null;
            try {
                $date = $this->dates->fromEnglishDate((string) $row['date_ad']);
            } catch (\Throwable) {
                $errors[] = "Row {$rowNumber}: date_ad could not be converted.";
            }

            if ($category && $account && $account->type !== Account::TYPE_FIXED_DEPOSIT && $date) {
                $amount = (int) $row['amount'];
                if ($type === 'expense') {
                    $runningBalances[$account->code] -= $amount;
                    if ($runningBalances[$account->code] < 0) {
                        $errors[] = "Row {$rowNumber}: Account balance cannot become negative.";
                    }
                }

                $rows[] = [
                    'row_number' => $rowNumber,
                    'date_ad' => (string) $row['date_ad'],
                    'date_bs' => $date['date_bs'],
                    'financial_year' => $date['financial_year'],
                    'category' => (string) $row['category'],
                    'category_name' => $category->name,
                    'account' => (string) $row['account'],
                    'account_name' => $account->name,
                    'amount' => $amount,
                    'reference' => $row['reference'] ?: null,
                    'note' => $row['note'] ?: null,
                ];
            }
        }

        if ($errors) {
            throw ValidationException::withMessages(['file' => $errors]);
        }

        if ($rows === []) {
            throw ValidationException::withMessages(['file' => 'The workbook contains no import rows.']);
        }

        return $rows;
    }

    public function post(string $type, array $rows, int $userId): int
    {
        return DB::transaction(function () use ($type, $rows, $userId) {
            foreach ($rows as $row) {
                $categoryModel = $type === 'income' ? IncomeCategory::class : ExpenseCategory::class;
                $category = $categoryModel::query()
                    ->where('code', $row['category'])
                    ->where('is_active', true)
                    ->first();
                $account = Account::query()
                    ->where('code', $row['account'])
                    ->where('is_active', true)
                    ->where('type', '!=', Account::TYPE_FIXED_DEPOSIT)
                    ->first();

                if (! $category || ! $account) {
                    throw new \RuntimeException(
                        "Row {$row['row_number']}: Category or account is no longer active. Upload and preview the workbook again."
                    );
                }
                $data = [
                    ($type === 'income' ? 'income_category_id' : 'expense_category_id') => $category->id,
                    'account_id' => $account->id,
                    'date_ad' => $row['date_ad'],
                    'date_bs' => $row['date_bs'],
                    'financial_year' => $row['financial_year'],
                    'amount' => $row['amount'],
                    'reference' => $row['reference'],
                    'note' => $row['note'],
                    'created_by' => $userId,
                ];

                if ($type === 'income') {
                    $this->incomeService->create($data);
                } else {
                    $this->expenseService->create($data);
                }
            }

            return count($rows);
        });
    }

    private function label(string $type): string
    {
        if (! in_array($type, ['income', 'expense'], true)) {
            throw new \InvalidArgumentException('Invalid import type.');
        }

        return ucfirst($type);
    }
}
