<x-app-layout>
<x-slot name="header"><div class="flex items-center justify-between"><div><h2 class="text-xl font-semibold text-gray-800">Account Transfers</h2><p class="mt-1 text-sm text-gray-500">Account Transfer Transactions</p></div>@if(auth()->user()->isAdmin()||auth()->user()->hasPermission('account-transfer.create'))<a href="{{ route('account-transfers.create') }}" class="rounded-md bg-gray-800 px-4 py-2 text-sm font-semibold text-white">+ New Transfer</a>@endif</div></x-slot>
<div class="py-6"><div class="mx-auto w-full px-4 sm:px-6 lg:px-8" style="max-width:1500px">@if(session('success'))<div class="mb-4 rounded-lg bg-green-50 p-4 text-sm text-green-700">{{ session('success') }}</div>@endif
<div class="overflow-hidden rounded-xl bg-white shadow-sm"><div class="border-b p-4"><form method="GET" action="{{ route('account-transfers.index') }}" class="flex flex-wrap items-end gap-3">
<div style="min-width:230px;flex:1 1 260px"><label for="search" class="mb-1 block text-xs font-medium">Search</label><input id="search" name="search" value="{{ $search }}" placeholder="Transfer or account..." class="w-full rounded-md border-gray-300 text-sm"></div>
@foreach([['from_account_id','From Account',$fromAccountId],['to_account_id','To Account',$toAccountId]] as [$field,$label,$selected])<div style="width:190px"><label for="{{ $field }}" class="mb-1 block text-xs font-medium">{{ $label }}</label><select id="{{ $field }}" name="{{ $field }}" class="w-full rounded-md border-gray-300 text-sm"><option value="">All Accounts</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected((string)$selected===(string)$account->id)>{{ $account->name }} ({{ $account->code }})</option>@endforeach</select></div>@endforeach
<div style="width:170px"><label for="financial_year" class="mb-1 block text-xs font-medium">Financial Year</label><select id="financial_year" name="financial_year" class="w-full rounded-md border-gray-300 text-sm"><option value="all" @selected(strtolower($financialYear)==='all')>All FY</option>@foreach($financialYears as $fy)<option value="{{ $fy }}" @selected($financialYear===$fy)>{{ $fy }}@if($fy===$currentFinancialYear) (Current)@endif</option>@endforeach</select></div>
<div style="width:145px"><label for="status" class="mb-1 block text-xs font-medium">Status</label><select id="status" name="status" class="w-full rounded-md border-gray-300 text-sm"><option value="active" @selected($status==='active')>Active</option><option value="cancelled" @selected($status==='cancelled')>Cancelled</option><option value="all" @selected($status==='all')>All</option></select></div>
<div style="width:160px"><label for="date_from" class="mb-1 block text-xs font-medium">From Date</label><input id="date_from" type="date" name="date_from" value="{{ $dateFrom }}" class="w-full rounded-md border-gray-300 text-sm"></div><div style="width:160px"><label for="date_to" class="mb-1 block text-xs font-medium">To Date</label><input id="date_to" type="date" name="date_to" value="{{ $dateTo }}" class="w-full rounded-md border-gray-300 text-sm"></div><button class="rounded-md bg-gray-800 px-5 py-2.5 text-sm font-semibold text-white">Filter</button><a href="{{ route('account-transfers.index') }}" class="rounded-md border border-gray-300 px-5 py-2.5 text-sm">Reset</a></form></div>
<div class="overflow-x-auto"><table class="min-w-full border-collapse"><thead class="bg-gray-50"><tr class="border-b text-left text-sm text-gray-600"><th class="px-4 py-3">Transfer</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">From Account</th><th class="px-4 py-3">To Account</th><th class="px-4 py-3 text-right">Amount</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Action</th></tr></thead><tbody>
@forelse($transfers as $transfer)<tr class="border-b border-gray-100"><td class="px-4 py-3 font-semibold">{{ $transfer->transfer_number }}</td><td class="whitespace-nowrap px-4 py-3">{{ $transfer->date_ad?->format('Y-m-d') ?? '-' }}<div class="text-xs text-gray-500">{{ $transfer->date_bs ?: '-' }}</div><div class="text-xs text-gray-400">FY {{ $transfer->financial_year ?: '-' }}</div></td><td class="px-4 py-3"><div class="font-medium text-red-700">{{ $transfer->fromAccount?->name ?? '-' }}</div><div class="text-xs text-gray-500">{{ $transfer->fromAccount?->code ?? '-' }}</div></td><td class="px-4 py-3"><div class="font-medium text-green-700">{{ $transfer->toAccount?->name ?? '-' }}</div><div class="text-xs text-gray-500">{{ $transfer->toAccount?->code ?? '-' }}</div></td><td class="px-4 py-3 text-right font-semibold">{{ number_format($transfer->amount) }}</td><td class="px-4 py-3"><span class="font-medium {{ $transfer->status==='active'?'text-green-700':'text-red-700' }}">{{ ucfirst($transfer->status) }}</span></td><td class="px-4 py-3 text-right"><a href="{{ route('account-transfers.show',$transfer) }}" class="text-blue-600 hover:underline">View</a></td></tr>@empty<tr><td colspan="7" class="px-4 py-12 text-center text-gray-500">No account transfers found.</td></tr>@endforelse
</tbody></table></div>@if($transfers->hasPages())<div class="border-t p-4">{{ $transfers->links() }}</div>@endif</div></div></div>
</x-app-layout>
